package springdocunexpectablenumberingsuffixchanginginspection.springdocunexpectablenumberingsuffixchanginginspection

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class SpringdocUnexpectableNumberingSuffixChangingInspectionApplication

fun main(args: Array<String>) {
	runApplication<SpringdocUnexpectableNumberingSuffixChangingInspectionApplication>(*args)
}
